version: "3.7"

services:

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "!MyComplexPassword"
      ACCEPT_EULA: "Y"
    networks:
      - graphqlstore

  webapi:
    container_name: webapi
    image: webapi
    build:
      context: .
      dockerfile: ./src/Dotnet5.GraphQL3.Store.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - 5000:5000
    networks:
      - graphqlstore
    depends_on:
      - mssql

  webmvc:
    container_name: webmvc
    image: webmvc
    build:
      context: .
      dockerfile: ./src/Dotnet5.GraphQL3.Store.WebMVC/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:7000
    ports:
      - 7000:7000
    networks:
      - graphqlstore
    depends_on:
      - webapi

networks:
  graphqlstore:
    driver: bridge